export const enum ActionTypes {
  CHANGE_SAME_COLUMN = "CHANGE_SAME_COLUMN",
  CHANGE_DIFF_COLUMN = "CHANGE_DIFF_COLUMN",
  FETCH_TASKS = "FETCH_TASKS",
  FETCH_ACCOUNTS = "FETCH_ACCOUNTS",
  ADD_INITIAL_TASKS = "ADD_INITIAL_TASKS",
  UPDATE_INITIAL_TASKS = "UPDATE_INITIAL_TASKS",
  ADD_TASK = "ADD_TASK",
  EDIT_TASK_TITLE = "EDIT_TASK_TITLE"
}
